# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-agent
  namespace: :YOUR_POD_NAMESPACE_NAME: #Eg: amazon-cloudwatch
  annotations:
    eks.amazonaws.com/role-arn: :IAM_ROLE_ARN: #Eg: arn:aws:iam::12345345:role/your-iam-role-name
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudwatch-agent-role
rules:
  # - apiGroups: [""]
  #   resources: ["pods", "nodes", "endpoints"]
  #   verbs: ["list", "watch"]
  # - apiGroups: ["apps"]
  #   resources: ["replicasets"]
  #   verbs: ["list", "watch"]
  # - apiGroups: ["batch"]
  #   resources: ["jobs"]
  #   verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/status", "pods/memory"]
    verbs: ["get"] 
  # - apiGroups: [""]
  #   resources: ["nodes/stats", "configmaps", "events"]
  #   verbs: ["create"]
  # - apiGroups: [""]
  #   resources: ["configmaps"]
  #   resourceNames: ["cwagent-clusterleader"]
  #   verbs: ["get","update"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudwatch-agent-role-binding
subjects:
  - kind: ServiceAccount
    name: cloudwatch-agent
    namespace: :YOUR_POD_NAMESPACE_NAME:
roleRef:
  kind: ClusterRole
  name: cloudwatch-agent-role
  apiGroup: rbac.authorization.k8s.io